title: Constructor University Robotics
description: Marine Robotics
theme: just-the-docs

url: https://constructor-robotics.github.io

aux_links:
  Template Repository: https://github.com/constructor-robotics/constructor-robotics.github.io